name: Python Compatibility Check

on: [push, pull_request]

jobs:
  check-syntax:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Check syntax with py_compile
      run: |
        for file in $(find . -name "*.py"); do
          python -m py_compile $file
        done
