name: Testing Windows

on:
  push:

jobs:
  test_job:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest] # ubuntu-latest, macos-latest,
        pythonVersion: [3.6, 3.7, 3.8]
        exclude:
          # - os: macos-latest
          #   pythonVersion: 3.8
          - os: windows-latest
            pythonVersion: 3.6
    steps:
    - uses: actions/checkout@v2
    - name: Anaconda-Action
      id: step1
      uses: fdiblen/anaconda-action@0.1.7
      with:
        envFileName: 'test_windows_env.yml'
    - name: Run Tests with pytest
      run: conda activate myenv  # Activate your conda environment
           pytest